<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Industry Pro Vault - Verse and Chorus</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        :root {
            --burgundy: #4c0519;
            --gold: #c5a059;
            --dark-bg: #0a0a0a;
            --card-bg: #161616;
            --sunset-orange: #f97316;
        }
        body { background-color: var(--dark-bg); color: #f4f4f4; font-family: 'Inter', sans-serif; }
        header { background-color: #000; padding: 40px 20px; text-align: center; border-bottom: 2px solid var(--gold); }
        .logo-main { font-size: 2.5rem; font-weight: bold; letter-spacing: 2px; text-transform: uppercase; }
        .logo-main span { color: var(--gold); }
        .song-card { background: var(--card-bg); border: 1px solid #27272a; border-radius: 12px; transition: all 0.3s ease; display: flex; flex-direction: column; }
        .song-card:hover { border-color: var(--gold); transform: translateY(-4px); }
        footer { background-color: #000; padding: 60px 20px; text-align: center; border-top: 2px solid var(--gold); margin-top: 60px; }
        .legal-box { background: rgba(197, 160, 89, 0.05); border: 1px solid rgba(197, 160, 89, 0.3); }
    </style>
</head>
<body>

<header>
    <div class="logo-main">VERSE <span>&</span> CHORUS</div>
    <div class="tracking-[4px] uppercase text-[0.9rem] text-[#c5a059] mt-2">Industry Pro Vault</div>
</header>

<main class="max-w-7xl mx-auto px-6 py-12">
    
    <section class="legal-box p-8 rounded-xl mb-12 shadow-2xl">
        <h2 class="text-[#c5a059] text-2xl font-bold mb-6">Rights & Licensing Assurance (For Industry Use)</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-8 text-sm text-gray-300">
            <div class="border-l-2 border-[#c5a059] pl-4">
                <strong class="text-white block mb-1 uppercase">✅ Royalty-Free Composition</strong>
                The instrumental and vocal placeholder track generated by Donna AI is covered by a Lifetime Royalty-Free Commercial License.
            </div>
            <div class="border-l-2 border-[#c5a059] pl-4">
                <strong class="text-white block mb-1 uppercase">✅ Guaranteed Lyric Ownership</strong>
                The lyrics are 100% human-authored by **Kellie Larson** and registered via Songbay.
            </div>
            <div class="border-l-2 border-[#c5a059] pl-4">
                <strong class="text-white block mb-1 uppercase">✅ Zero Future AI Royalties</strong>
                No performance or mechanical royalties will ever be owed to the AI platform owner for these demos.
            </div>
            <div class="border-l-2 border-[#c5a059] pl-4">
                <strong class="text-white block mb-1 uppercase">✅ Immediate Clearance</strong>
                All material is pre-cleared for commercial development and Sync Licensing.
            </div>
        </div>
    </section>

    <div class="mb-10 p-6 bg-[#121212] rounded-xl border border-gray-800">
        <h3 class="text-gray-400 uppercase tracking-widest text-xs font-bold mb-4">Deep Metadata Search</h3>
        <input type="text" id="searchBar" placeholder="Search by Mood, POV, Placement, or Lyric keywords (e.g. 'Betrayal', 'Vengeance', 'Spoken Word')..." 
               class="w-full bg-black border border-gray-700 rounded-lg p-4 outline-none text-white focus:border-orange-500 transition-all">
        <div class="flex justify-between mt-3 px-1">
            <p class="text-xs text-gray-500">Searching 47 tracks: Full Lyrics, Mood, Genre, and Descriptions included.</p>
            <p id="resultCount" class="text-xs text-[#c5a059] font-bold"></p>
        </div>
    </div>

    <div id="catalog-grid" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        </div>
</main>

<footer>
    <div class="text-[1.8rem] text-[#c5a059] mb-1">Kellie Larson</div>
    <div class="tracking-[3px] uppercase text-[0.85rem] text-gray-400 mb-6">Cinematic Songwriter and Lyricist</div>
    <div class="flex flex-col md:flex-row justify-center items-center gap-4 md:gap-8 text-sm border-t border-gray-900 pt-6">
        <a href="tel:760-537-0222" class="hover:text-white transition">760-537-0222</a>
        <a href="mailto:info@verseandchorus.com" class="hover:text-white transition">info@verseandchorus.com</a>
    </div>
    <div class="mt-8 text-[0.7rem] text-gray-600">&copy; 2025 Verse and Chorus | All Rights Reserved</div>
</footer>

<script>
    // Instruction-based Title Updates
    const titleUpdates = {
        "Tick Tok": "The Real Dream Team",
        "Hubba Bubba song": "Heartbreak and Trouble",
        "Just": "Just A Little Lonely",
        "Too Much": "Just Too Much",
        "Fury": "Fury (I'm the Monster)",
        "When Misty Cries": "Your Forever Man",
        "Miss Your Stupid Face": "Etched in Every Space",
        "Sick One": "Sick One (s1c)",
        "Not Clever": "I Know Your Damn Pin Code",
        "Boys Boys Boys": "CEO NOT A BABYSITTING TREE"
    };

    let songData = [];

    async function initVault() {
        try {
            const response = await fetch('lyrics.json');
            if (!response.ok) throw new Error("lyrics.json failed to load");
            songData = await response.json();
            renderCatalog(songData); // Show all 47 cards by default
        } catch (e) {
            console.error(e);
            document.getElementById('catalog-grid').innerHTML = `<div class="col-span-full text-center py-20 text-red-500">Error: Could not load lyrics.json. Please ensure the file is in the same folder.</div>`;
        }
    }

    function renderCatalog(songs) {
        const grid = document.getElementById('catalog-grid');
        const countDisplay = document.getElementById('resultCount');
        
        countDisplay.textContent = `Showing ${songs.length} Tracks`;

        grid.innerHTML = songs.map(song => {
            // Apply Title rules
            const displayTitle = titleUpdates[song.title] || song.title;
            const genres = [song.genre1, song.genre2].filter(g => g && g !== 'Placeholder').join(' / ');

            return `
                <div class="song-card p-6">
                    <div class="flex-grow">
                        <div class="flex justify-between items-start mb-4">
                            <h3 class="text-xl font-bold text-orange-500 uppercase tracking-tight">${displayTitle}</h3>
                            <span class="bg-gray-800 text-gray-500 px-2 py-0.5 rounded text-[10px]">ID: ${song.id || 'N/A'}</span>
                        </div>
                        
                        <div class="grid grid-cols-2 gap-y-1 mb-6 text-[0.75rem] text-gray-400">
                            <div><span class="text-gray-600 block uppercase text-[9px]">Genre</span> ${genres || 'N/A'}</div>
                            <div><span class="text-gray-600 block uppercase text-[9px]">POV</span> ${song.pov || 'N/A'}</div>
                            <div><span class="text-gray-600 block uppercase text-[9px]">Mood</span> ${song.moodTone || 'N/A'}</div>
                            <div><span class="text-gray-600 block uppercase text-[9px]">Placement</span> ${song.placementType || 'N/A'}</div>
                        </div>

                        <div class="mb-6 p-3 bg-black/40 rounded border border-gray-800">
                            <p class="text-[0.8rem] text-gray-300 italic line-clamp-3">
                                "${song.shortDescription || 'Placeholder'}"
                            </p>
                        </div>
                    </div>

                    <div class="flex gap-2 mt-auto">
                        <button class="flex-1 bg-orange-600 hover:bg-orange-700 text-white text-xs font-bold py-2.5 rounded transition shadow-lg" 
                                onclick="window.open('${song.songbayWebpageUrl}', '_blank')">
                            READ LYRICS & LICENSE
                        </button>
                        <button class="px-4 border border-gray-700 rounded text-gray-400 hover:bg-gray-800 transition" 
                                title="Print Details" onclick="window.print()">
                            🖨️
                        </button>
                    </div>
                </div>
            `;
        }).join('');
    }

    // Deep Search Logic: Includes fullTextLyrics, Mood, Genre, etc.
    document.getElementById('searchBar').addEventListener('input', (e) => {
        const term = e.target.value.toLowerCase().trim();
        
        if (!term) {
            renderCatalog(songData);
            return;
        }

        const filtered = songData.filter(s => {
            const combinedString = [
                s.title,
                s.genre1,
                s.genre2,
                s.moodTone,
                s.placementType,
                s.pov,
                s.fullLyrics, // Searchable full text lyrics
                s.shortDescription,
                s.longDescription
            ].join(' ').toLowerCase();

            return combinedString.includes(term);
        });

        renderCatalog(filtered);
    });

    window.onload = initVault;
</script>
</body>
</html>
