<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Industry Pro Vault - Verse and Chorus</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        :root {
            --burgundy: #4c0519;
            --gold: #c5a059;
            --dark-bg: #0a0a0a;
            --card-bg: #161616;
            --sunset-orange: #f97316;
        }
        body { background-color: var(--dark-bg); color: #f4f4f4; font-family: 'Inter', sans-serif; }
        header { background-color: #000; padding: 40px 20px; text-align: center; border-bottom: 2px solid var(--gold); }
        .logo-main { font-size: 2.5rem; font-weight: bold; letter-spacing: 2px; text-transform: uppercase; }
        .logo-main span { color: var(--gold); }
        .song-card { background: var(--card-bg); border: 1px solid #27272a; border-radius: 12px; transition: all 0.3s ease; display: flex; flex-direction: column; }
        .song-card:hover { border-color: var(--gold); transform: translateY(-4px); }
        footer { background-color: #000; padding: 60px 20px; text-align: center; border-top: 2px solid var(--gold); margin-top: 60px; }
        .legal-box { background: rgba(197, 160, 89, 0.05); border: 1px solid rgba(197, 160, 89, 0.3); }
    </style>
</head>
<body>

<header>
    <div class="logo-main">VERSE <span>&</span> CHORUS</div>
    <div class="tracking-[4px] uppercase text-[0.9rem] text-[#c5a059] mt-2">Industry Pro Vault</div>
</header>

<main class="max-w-7xl mx-auto px-6 py-12">
    
    <section class="legal-box p-8 rounded-xl mb-12 shadow-2xl">
        <h2 class="text-[#c5a059] text-2xl font-bold mb-6 text-center">Rights & Licensing Assurance (For Industry Use)</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-8 text-sm text-gray-300">
            <div class="border-l-2 border-[#c5a059] pl-4">
                <strong class="text-white block mb-1 uppercase">✅ Royalty-Free Composition</strong>
                The instrumental and vocal placeholder track generated by Donna AI is covered by a Lifetime Royalty-Free Commercial License.
            </div>
            <div class="border-l-2 border-[#c5a059] pl-4">
                <strong class="text-white block mb-1 uppercase">✅ Guaranteed Lyric Ownership</strong>
                The lyrics are 100% human-authored by **Kellie Larson** and registered via Songbay.
            </div>
            <div class="border-l-2 border-[#c5a059] pl-4">
                <strong class="text-white block mb-1 uppercase">✅ Zero Future Royalties from AI</strong>
                Your company will never owe performance or mechanical royalties to the AI platform owner for these demos.
            </div>
            <div class="border-l-2 border-[#c5a059] pl-4">
                <strong class="text-white block mb-1 uppercase">✅ Immediate Clearance</strong>
                All material is pre-cleared for commercial development and Sync Licensing.
            </div>
        </div>
    </section>

    <div class="mb-10 p-6 bg-[#121212] rounded-xl border border-gray-800">
        <h3 class="text-gray-400 uppercase tracking-widest text-xs font-bold mb-4 text-center">Global Catalog Search</h3>
        <input type="text" id="searchBar" placeholder="Search by POV, Mood, Placement, or Lyric keywords..." 
               class="w-full bg-black border border-gray-700 rounded-lg p-4 outline-none text-white focus:border-orange-500 transition-all shadow-inner">
        <p class="text-[10px] text-gray-500 mt-3 text-center uppercase tracking-widest">Searching Full Lyrics, Genre 1 & 2, POV, Mood, and Descriptions.</p>
    </div>

    <div id="catalog-grid" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        </div>
</main>

<footer>
    <div class="text-[1.8rem] text-[#c5a059] mb-1">Kellie Larson</div>
    <div class="tracking-[3px] uppercase text-[0.85rem] text-gray-400 mb-6">Cinematic Songwriter and Lyricist</div>
    <div class="flex flex-col md:flex-row justify-center items-center gap-4 md:gap-8 text-sm border-t border-gray-900 pt-6">
        <a href="tel:760-537-0222" class="hover:text-white transition">760-537-0222</a>
        <a href="mailto:info@verseandchorus.com" class="hover:text-white transition">info@verseandchorus.com</a>
    </div>
    <div class="mt-8 text-[0.7rem] text-gray-600">&copy; 2025 Verse and Chorus | All Rights Reserved</div>
</footer>

<script>
    // AUTOMATIC TITLE UPDATES
    const titleUpdates = {
        "Tick Tok": "The Real Dream Team",
        "Hubba Bubba song": "Heartbreak and Trouble",
        "Just": "Just A Little Lonely",
        "Too Much": "Just Too Much",
        "Fury": "Fury (I'm the Monster)",
        "When Misty Cries": "Your Forever Man",
        "Miss Your Stupid Face": "Etched in Every Space",
        "Sick One": "Sick One (s1c)",
        "Not Clever": "I Know Your Damn Pin Code",
        "Boys Boys Boys": "CEO NOT A BABYSITTING TREE"
    };

    // DIRECT DATA LOAD: Pasting your lyrics.json data directly here to solve "File Not Found" errors
    const songData = [
        { "id": 1, "title": "AUTHOR OF A LIE", "genre1": "Pop", "genre2": "Hip-Hop", "moodTone": "Anthemic, Confident", "pov": "1st Person Female", "placementType": "Punchy Track / Commercial Sync", "shortDescription": "Highly confrontational and sarcastic fusion tracking the dismantling of a false narrative.", "fullLyrics": "You tell a story, i pick it apart... master of deceit... tired of this story on repeat." },
        { "id": 2, "title": "BIG HARD NO", "genre1": "Country", "genre2": "Contemporary Country", "moodTone": "Anthemic, Confident, Determined", "pov": "1st Person Female", "placementType": "Fiery Anthem / Potential Single", "shortDescription": "Fierce, definitive response to a past lover combining betrayal with self-worth.", "fullLyrics": "That's a big hard NO... Nothing you could whisper can ever douse this flame." },
        { "id": 3, "title": "BOOM BOOM BEAT", "genre1": "Pop", "genre2": "General Dance", "moodTone": "Bouncy, Fun, Romantic", "pov": "1st Person (Ambiguous)", "placementType": "Catchy Hook / Commercial Sync", "shortDescription": "Upbeat pop song centered on the anticipation of reuniting with a loved one.", "fullLyrics": "Boom, boom, boom, da boom, boom, boom... Yodel-ay-hee-hoo!" },
        { "id": 4, "title": "BROKEN RECORD", "genre1": "Rock", "genre2": "Alt-Rock", "moodTone": "Anthemic, Bitter, Confident", "pov": "1st Person (Ambiguous)", "placementType": "Visceral Anthem / Film/TV Placement", "shortDescription": "Raw anthem of self-reclamation moving from defeat to a defiant turning point.", "fullLyrics": "I'm a broken record, skipping on repeat... bitter taste of defeat." },
        { "id": 5, "title": "Boys Boys Boys", "genre1": "Pop", "genre2": "R&B", "moodTone": "Confident, Fun, Playful", "pov": "1st Person Female", "placementType": "Viral / Streaming Hit", "shortDescription": "Contrasts dating immature 'boys' with the desire for a sophisticated 'man.'", "fullLyrics": "Honey, I'm a CEO, not a babysitting tree... boys, boys, boys." },
        { "id": 6, "title": "CHILDREN OF WAR", "genre1": "Folk", "genre2": "Contemporary Folk", "moodTone": "Anthemic, Dark, Haunting", "pov": "3rd Person", "placementType": "Dramatic Soundtrack / Narrative Ballad", "shortDescription": "Urgent social commentary on the devastating impact of global conflict.", "fullLyrics": "Run, little children! there's nothing left here... dreams turn to ash." },
        { "id": 10, "title": "Miss Your Stupid Face", "genre1": "Easy Listening", "genre2": "Pop Ballad", "moodTone": "Introspective, Mournful, Sad", "pov": "1st Person Female", "placementType": "Soulful Ballad", "shortDescription": "Power ballad detailing the suffocating pain of grief after an irreplaceable loss.", "fullLyrics": "Oh, i miss your stupid face! it's etched in every space." },
        { "id": 12, "title": "Fury", "genre1": "Alternative and Punk", "genre2": "Pop-Punk", "moodTone": "Angry, Dramatic, Hard", "pov": "1st Person Female", "placementType": "Crunk Punk / Cinematic Tension", "shortDescription": "Unyielding narrative detailing physical and emotional torment and self-rescue.", "fullLyrics": "Oh, the fury! please save me! i'm about to roll right over your body and run." },
        { "id": 30, "title": "Sick One", "genre1": "Rock", "genre2": "General Alternative", "moodTone": "Bitter, Confident, Cool", "pov": "1st Person (Ambiguous)", "placementType": "Raw Confessional / Alternative Rock", "shortDescription": "Raw, unflinching exploration of a toxic love addiction cycle.", "fullLyrics": "Our love is on a sick one... I run back. Right on cue." },
        { "id": 41, "title": "When Misty Cries", "genre1": "Country", "genre2": "Alternative Country", "moodTone": "Confident, Mellow, Romantic", "pov": "1st Person Male", "placementType": "Heartfelt Ballad / Relationship Sync", "shortDescription": "Heartfelt ballad about a man's unwavering commitment to his partner's healing.", "fullLyrics": "When Misty cries, the tears fall like rain... I'm her forever man." }
        // ... (Add your remaining tracks here to reach all 47)
    ];

    function renderCatalog(songs) {
        const grid = document.getElementById('catalog-grid');
        grid.innerHTML = songs.map(song => {
            // Apply Title correction logic
            const displayTitle = titleUpdates[song.title] || song.title;
            const genres = [song.genre1, song.genre2].filter(g => g && g !== 'Placeholder').join(' / ');

            return `
                <div class="song-card p-6">
                    <div class="flex-grow">
                        <div class="flex justify-between items-start mb-4">
                            <h3 class="text-xl font-bold text-orange-500 uppercase tracking-tighter">${displayTitle}</h3>
                            <span class="bg-gray-800 text-gray-600 px-2 py-1 rounded text-[9px] font-mono">ID: ${song.id}</span>
                        </div>
                        
                        <div class="grid grid-cols-2 gap-4 mb-6 text-[0.7rem] text-gray-500 uppercase font-bold tracking-widest">
                            <div><span class="text-gray-700 block text-[8px]">Genre</span> ${genres}</div>
                            <div><span class="text-gray-700 block text-[8px]">POV</span> ${song.pov || 'N/A'}</div>
                            <div><span class="text-gray-700 block text-[8px]">Mood</span> ${song.moodTone || 'N/A'}</div>
                            <div><span class="text-gray-700 block text-[8px]">Placement</span> ${song.placementType || 'N/A'}</div>
                        </div>

                        <div class="p-3 bg-black/50 rounded-lg border border-gray-900 mb-6">
                            <p class="text-[0.8rem] text-gray-400 italic">"${song.shortDescription || 'Placeholder'}"</p>
                        </div>
                    </div>

                    <div class="flex gap-2">
                        <button class="flex-1 bg-orange-600 hover:bg-orange-700 text-white text-[10px] font-black py-3 rounded-md transition shadow-lg">READ FULL LYRICS</button>
                        <button class="px-4 border border-gray-800 rounded-md text-gray-500 hover:bg-gray-900 transition" onclick="window.print()">🖨️</button>
                    </div>
                </div>
            `;
        }).join('');
    }

    // SEARCH ALL FIELDS: Title, Lyrics, Mood, POV, Genre, Placement
    document.getElementById('searchBar').addEventListener('input', (e) => {
        const term = e.target.value.toLowerCase().trim();
        const filtered = songData.filter(s => {
            const combined = [
                s.title, s.genre1, s.genre2, s.moodTone, s.placementType, 
                s.pov, s.fullLyrics, s.shortDescription
            ].join(' ').toLowerCase();
            return combined.includes(term);
        });
        renderCatalog(filtered);
    });

    // Default Load on Start
    window.onload = () => renderCatalog(songData);
</script>
</body>
</html>
