<?php 
// 1. Set the specific page title for this page (used in the <title> tag)
$page_title = 'Industry Pro Vault';

// 2. Include the Header (includes config.php, opens <html>, <head>, <body>, <header>, and <main> tags)
include 'header.php'; 
?>

<div class="mb-10 pt-4">
        <div class="page-title-block">
            <h2 class="text-4xl font-extrabold tracking-widest text-white ml-4">INDUSTRY PRO VAULT</h2>
        </div>
        <p class="text-lg mt-2 text-gray-300 ml-4">Curated catalog for A&R and sync professionals</p>
    </div>
    
    <div class="bg-[var(--burgundy)] p-8 mb-12 rounded-xl shadow-2xl text-center border-6 border-gray-400">
        <h3 class="text-2xl font-bold header-gold mb-3">Welcome to the Vault</h3>
        <p class="text-gray-100 max-w-3xl mx-auto">
            This exclusive section provides fully licensed, pre-cleared assets ready for immediate commercial development. Our system ensures clear IP ownership and royalty-free composition for all placeholder demos, streamlining your path to full copyright.
        </p>
        <button class="mt-5 mx-2 btn-orange font-bold py-2 px-6 rounded-full">
            Explore Licensing Options
        </button>
        <a href="/reports.html" class="inline-block mt-5 mx-2 btn-orange font-bold py-2 px-6 rounded-full">
            Click to Transfer: Lyric Audit Report
        </a>
    </div>

    <div class="legal-box p-6 mb-10">
        <h4 class="text-xl font-bold header-gold mb-4">Rights & Licensing Assurance (For Industry Use)</h4>
        
        <p class="mb-6 text-gray-300">To ensure a seamless, low-risk process for A&R and Sync partners, we offer the following guarantees for all placeholder demos:</p>

        <ul class="text-sm text-gray-300">
            <li><strong class="text-white">✅ Royalty-Free Composition:</strong> The instrumental and vocal placeholder track generated by Donna AI is covered by a Lifetime Royalty-Free Commercial License. This eliminates all recurring sync or master use fees for the underlying AI composition.</li>
            <li><strong class="text-white">✅ Guaranteed Lyric Ownership:</strong> The lyrics are 100% human-authored and registered via Songbay, providing clear, verifiable intellectual property (IP) protection and ownership before any further development.</li>
            <li><strong class="text-white">✅ Zero Future Royalties from AI:</strong> Your label/production company will never owe performance or mechanical royalties to the AI platform owner (Mobiversite/Donna AI) for the use of the demo.</li>
            <li><strong class="text-white">✅ Simple Path to Full Copyright:</strong> Once you sign the song and re-record the music (replacing the AI vocals/instruments), the song becomes a new, fully human-authored derivative work based on our copyrighted lyrics, providing your company with full, traditional copyright ownership over the final master and publishing.</li>
            <li><strong class="text-white">✅ Immediate Clearance:</strong> All material is pre-cleared for commercial development and Sync Licensing under the terms of our active PRO subscription. Proof of License (PoC) available instantly upon request.</li>
        </ul>
    </div>
    
    <div class="flex flex-wrap justify-between items-center bg-gray-900 p-4 rounded-lg mb-4 text-white shadow-lg border-4 border-gray-400">
        <div class="text-lg font-semibold header-gold mb-4 sm:mb-0">Filter Catalog:</div>
        <div class="flex flex-wrap gap-2 text-sm">
            <select class="p-2 bg-white border border-gray-400 rounded-md text-black focus:ring-1 focus:ring-[var(--burgundy)]">
                <option>Genre</option>
                <option>Pop</option>
                <option>Rock</option>
                <option>Electronic</option>
                <option>Folk</option>
            </select>
            <select class="p-2 bg-white border border-gray-400 rounded-md text-black focus:ring-1 focus:ring-[var(--burgundy)]">
                <option>Mood</option>
                <option>Uplifting</option>
                <option>Melancholy</option>
                <option>Frustrated</option>
                <option>Defiant</option>
                <option>Romantic</option>
                <option>Reflective</option>
                <option>Restless</option>
                <option>Purposeful</option>
            </select>
            <select class="p-2 bg-white border border-gray-400 rounded-md text-black focus:ring-1 focus:ring-[var(--burgundy)]">
                <option>Theme (A&R Category)</option>
                <option>Gaslighting</option>
                <option>Empowerment</option>
                <option>Reunion</option>
                <option>Loss of Market Share</option>
                <option>Narrative of Disenchantment</option>
                <option>Narrative of Iteration</option>
                <option>Social Commentary</option>
                <option>Empowerment Arc</option>
            </select>
            <button class="btn-orange text-white font-semibold py-2 px-4 rounded-md">Filter</button>
            <button class="bg-gray-700 hover:bg-gray-600 text-white font-semibold py-2 px-4 rounded-md">Reset</button>
        </div>
    </div>

    <p class="text-right text-sm mb-6"><a href="#top" class="link-orange hover:underline">↑ Back to Top</a></p>

    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
        <div class="song-item p-4 bg-gray-800 rounded-lg shadow-xl hover:shadow-2xl transition duration-300 scratched-border">
            <img src="covers/author-of-a-lie-cover-art.jpg" alt="Author of a Lie cover art" class="mx-auto mb-4">
            <h3 class="text-xl font-bold text-slate-200 mb-1">Author of a Lie</h3>
            <p class="text-xs text-gray-400 mb-3">Genre: Pop | Mood: Frustrated | Theme: Gaslighting</p>
            <p class="text-sm italic text-gray-300">PLACEHOLDER</p>
            <div class="mt-4 text-gray-400 font-semibold flex justify-end">
                <a href="#" class="link-orange hover:underline">🖨️ Print Lyric</a>
            </div>
        </div>
        <div class="song-item p-4 bg-gray-800 rounded-lg shadow-xl hover:shadow-2xl transition duration-300 scratched-border">
            <img src="covers/big-hard-no-cover-art.jpg" alt="Big Hard No cover art" class="mx-auto mb-4">
            <h3 class="text-xl font-bold text-slate-200 mb-1">Big Hard No</h3>
            <p class="text-xs text-gray-400 mb-3">Genre: Pop | Mood: Defiant | Theme: Empowerment</p>
            <p class="text-sm italic text-gray-300">PLACEHOLDER</p>
            <div class="mt-4 text-gray-400 font-semibold flex justify-end">
                <a href="#" class="link-orange hover:underline">🖨️ Print Lyric</a>
            </div>
        </div>
        <div class="song-item p-4 bg-gray-800 rounded-lg shadow-xl hover:shadow-2xl transition duration-300 scratched-border">
            <img src="covers/boom-boom-beat-cover-art.jpg" alt="Boom Boom Beat cover art" class="mx-auto mb-4">
            <h3 class="text-xl font-bold text-slate-200 mb-1">Boom Boom Beat</h3>
            <p class="text-xs text-gray-400 mb-3">Genre: Pop | Mood: Romantic | Theme: Reunion</p>
            <p class="text-sm italic text-gray-300">PLACEHOLDER</p>
            <div class="mt-4 text-gray-400 font-semibold flex justify-end">
                <a href="#" class="link-orange hover:underline">🖨️ Print Lyric</a>
            </div>
        </div>
        <div class="song-item p-4 bg-gray-800 rounded-lg shadow-xl hover:shadow-2xl transition duration-300 scratched-border">
            <img src="covers/the-devaluation-event-cover-art.jpg" alt="The Devaluation Event cover art" class="mx-auto mb-4">
            <h3 class="text-xl font-bold text-slate-200 mb-1">The Devaluation Event</h3>
            <p class="text-xs text-gray-400 mb-3">Genre: Electronic | Mood: Melancholy | Theme: Loss of Market Share</p>
            <p class="text-sm italic text-gray-300">PLACEHOLDER</p>
            <div class="mt-4 text-gray-400 font-semibold flex justify-end">
                <a href="#" class="link-orange hover:underline">🖨️ Print Lyric</a>
            </div>
        </div>
        <div class="song-item p-4 bg-gray-800 rounded-lg shadow-xl hover:shadow-2xl transition duration-300 scratched-border">
            <img src="covers/disenchanted-cover-art.jpg" alt="Disenchanted cover art" class="mx-auto mb-4">
            <h3 class="text-xl font-bold text-slate-200 mb-1">Disenchanted</h3>
            <p class="text-xs text-gray-400 mb-3">Genre: Rock | Mood: Reflective | Theme: Narrative of Disenchantment</p>
            <p class="text-sm italic text-gray-300">PLACEHOLDER</p>
            <div class="mt-4 text-gray-400 font-semibold flex justify-end">
                <a href="#" class="link-orange hover:underline">🖨️ Print Lyric</a>
            </div>
        </div>
        <div class="song-item p-4 bg-gray-800 rounded-lg shadow-xl hover:shadow-2xl transition duration-300 scratched-border">
            <img src="covers/iteration-cover-art.jpg" alt="Iteration cover art" class="mx-auto mb-4">
            <h3 class="text-xl font-bold text-slate-200 mb-1">Iteration</h3>
            <p class="text-xs text-gray-400 mb-3">Genre: Pop | Mood: Restless | Theme: Narrative of Iteration</p>
            <p class="text-sm italic text-gray-300">PLACEHOLDER</p>
            <div class="mt-4 text-gray-400 font-semibold flex justify-end">
                <a href="#" class="link-orange hover:underline">🖨️ Print Lyric</a>
            </div>
        </div>
        <div class="song-item p-4 bg-gray-800 rounded-lg shadow-xl hover:shadow-2xl transition duration-300 scratched-border">
            <img src="covers/power-of-the-pen-cover-art.jpg" alt="Power of the Pen cover art" class="mx-auto mb-4">
            <h3 class="text-xl font-bold text-slate-200 mb-1">Power of the Pen</h3>
            <p class="text-xs text-gray-400 mb-3">Genre: Folk | Mood: Purposeful | Theme: Social Commentary</p>
            <p class="text-sm italic text-gray-300">PLACEHOLDER</p>
            <div class="mt-4 text-gray-400 font-semibold flex justify-end">
                <a href="#" class="link-orange hover:underline">🖨️ Print Lyric</a>
            </div>
        </div>
        <div class="song-item p-4 bg-gray-800 rounded-lg shadow-xl hover:shadow-2xl transition duration-300 scratched-border">
            <img src="covers/journey-to-agency-cover-art.jpg" alt="Journey to Agency cover art" class="mx-auto mb-4">
            <h3 class="text-xl font-bold text-slate-200 mb-1">Journey to Agency</h3>
            <p class="text-xs text-gray-400 mb-3">Genre: Pop | Mood: Uplifting | Theme: Empowerment Arc</p>
            <p class="text-sm italic text-gray-300">PLACEHOLDER</p>
            <div class="mt-4 text-gray-400 font-semibold flex justify-end">
                <a href="#" class="link-orange hover:underline">🖨️ Print Lyric</a>
            </div>
        </div>
        </div>

    <p class="text-right text-sm mt-8"><a href="#top" class="link-orange hover:underline">↑ Back to Top</a></p>
    
<?php 
// 3. Include the Footer (closes <main>, <footer>, and </body>, </html> tags)
include 'footer.php'; 
?>
